"""baseline schema

Revision ID: 6df6ce6bdd8b
Revises: 
Create Date: 2026-08-28 17:37:43.484732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df6ce6bdd8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_username'), ['username'], unique=True)

    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('medium', sa.String(length=60), nullable=True),
    sa.Column('campaign', sa.String(length=160), nullable=True),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('props', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_page'), ['page'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_session_id'), ['session_id'], unique=False)

    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('medium', sa.String(length=60), nullable=True),
    sa.Column('campaign', sa.String(length=160), nullable=True),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_session_id'), ['session_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('service', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('value_estimate', sa.Integer(), nullable=True),
    sa.Column('lost_reason', sa.String(length=120), nullable=True),
    sa.Column('won_at', sa.DateTime(), nullable=True),
    sa.Column('lost_at', sa.DateTime(), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('medium', sa.String(length=60), nullable=True),
    sa.Column('campaign', sa.String(length=160), nullable=True),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_next_followup_at'), ['next_followup_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)

    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_visible'), ['visible'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_visible'), ['visible'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('tagline', sa.String(length=240), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('hero_path', sa.String(length=255), nullable=True),
    sa.Column('hero_type', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.String(length=64), nullable=False),
    sa.Column('start_at_utc', sa.DateTime(), nullable=False),
    sa.Column('end_at_utc', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_at_utc', name='uq_bookings_start_at_utc')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_id'), ['booking_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    op.create_table('lead_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_notes_lead_id'), ['lead_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_notes_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_notes_created_at'))

    op.drop_table('lead_notes')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_email'))
        batch_op.drop_index(batch_op.f('ix_bookings_created_at'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_id'))

    op.drop_table('bookings')
    op.drop_table('settings')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_visible'))
        batch_op.drop_index(batch_op.f('ix_projects_position'))

    op.drop_table('projects')
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_visible'))
        batch_op.drop_index(batch_op.f('ix_links_position'))

    op.drop_table('links')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_session_id'))
        batch_op.drop_index(batch_op.f('ix_leads_next_followup_at'))
        batch_op.drop_index(batch_op.f('ix_leads_name'))
        batch_op.drop_index(batch_op.f('ix_leads_is_archived'))
        batch_op.drop_index(batch_op.f('ix_leads_email'))
        batch_op.drop_index(batch_op.f('ix_leads_created_at'))

    op.drop_table('leads')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_is_read'))

    op.drop_table('contact_messages')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_page'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_event'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_created_at'))

    op.drop_table('analytics_events')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_username'))

    op.drop_table('admin')
    # ### end Alembic commands ###
